//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tmag.GvcPassThroughApi.GvCommerce {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceBookItem", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class PriceBookItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLLargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLRegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLSmallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLThumbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ItemPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SetPieceCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShaftTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShaftTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURLLarge {
            get {
                return this.ImageURLLargeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLLargeField, value) != true)) {
                    this.ImageURLLargeField = value;
                    this.RaisePropertyChanged("ImageURLLarge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURLReg {
            get {
                return this.ImageURLRegField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLRegField, value) != true)) {
                    this.ImageURLRegField = value;
                    this.RaisePropertyChanged("ImageURLReg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURLSmall {
            get {
                return this.ImageURLSmallField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLSmallField, value) != true)) {
                    this.ImageURLSmallField = value;
                    this.RaisePropertyChanged("ImageURLSmall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURLThumb {
            get {
                return this.ImageURLThumbField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLThumbField, value) != true)) {
                    this.ImageURLThumbField = value;
                    this.RaisePropertyChanged("ImageURLThumb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ItemPrice {
            get {
                return this.ItemPriceField;
            }
            set {
                if ((this.ItemPriceField.Equals(value) != true)) {
                    this.ItemPriceField = value;
                    this.RaisePropertyChanged("ItemPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModelID {
            get {
                return this.ModelIDField;
            }
            set {
                if ((this.ModelIDField.Equals(value) != true)) {
                    this.ModelIDField = value;
                    this.RaisePropertyChanged("ModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductTypeID {
            get {
                return this.ProductTypeIDField;
            }
            set {
                if ((this.ProductTypeIDField.Equals(value) != true)) {
                    this.ProductTypeIDField = value;
                    this.RaisePropertyChanged("ProductTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductTypeName {
            get {
                return this.ProductTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeNameField, value) != true)) {
                    this.ProductTypeNameField = value;
                    this.RaisePropertyChanged("ProductTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SetPieceCount {
            get {
                return this.SetPieceCountField;
            }
            set {
                if ((this.SetPieceCountField.Equals(value) != true)) {
                    this.SetPieceCountField = value;
                    this.RaisePropertyChanged("SetPieceCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShaftTypeID {
            get {
                return this.ShaftTypeIDField;
            }
            set {
                if ((this.ShaftTypeIDField.Equals(value) != true)) {
                    this.ShaftTypeIDField = value;
                    this.RaisePropertyChanged("ShaftTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShaftTypeName {
            get {
                return this.ShaftTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShaftTypeNameField, value) != true)) {
                    this.ShaftTypeNameField = value;
                    this.RaisePropertyChanged("ShaftTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceBookFault", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class PriceBookFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceBookRequest", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class PriceBookRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModelIDField;
        
        private int ProductTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShaftTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModelID {
            get {
                return this.ModelIDField;
            }
            set {
                if ((this.ModelIDField.Equals(value) != true)) {
                    this.ModelIDField = value;
                    this.RaisePropertyChanged("ModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductTypeID {
            get {
                return this.ProductTypeIDField;
            }
            set {
                if ((this.ProductTypeIDField.Equals(value) != true)) {
                    this.ProductTypeIDField = value;
                    this.RaisePropertyChanged("ProductTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShaftTypeID {
            get {
                return this.ShaftTypeIDField;
            }
            set {
                if ((this.ShaftTypeIDField.Equals(value) != true)) {
                    this.ShaftTypeIDField = value;
                    this.RaisePropertyChanged("ShaftTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductType", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class ProductType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductTypeID {
            get {
                return this.ProductTypeIDField;
            }
            set {
                if ((this.ProductTypeIDField.Equals(value) != true)) {
                    this.ProductTypeIDField = value;
                    this.RaisePropertyChanged("ProductTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Brand", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class Brand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Model", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class Model : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLLargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLRegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLSmallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLThumbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURLLarge {
            get {
                return this.ImageURLLargeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLLargeField, value) != true)) {
                    this.ImageURLLargeField = value;
                    this.RaisePropertyChanged("ImageURLLarge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURLReg {
            get {
                return this.ImageURLRegField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLRegField, value) != true)) {
                    this.ImageURLRegField = value;
                    this.RaisePropertyChanged("ImageURLReg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURLSmall {
            get {
                return this.ImageURLSmallField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLSmallField, value) != true)) {
                    this.ImageURLSmallField = value;
                    this.RaisePropertyChanged("ImageURLSmall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURLThumb {
            get {
                return this.ImageURLThumbField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLThumbField, value) != true)) {
                    this.ImageURLThumbField = value;
                    this.RaisePropertyChanged("ImageURLThumb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModelID {
            get {
                return this.ModelIDField;
            }
            set {
                if ((this.ModelIDField.Equals(value) != true)) {
                    this.ModelIDField = value;
                    this.RaisePropertyChanged("ModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShaftType", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class ShaftType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShaftTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShaftTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShaftTypeID {
            get {
                return this.ShaftTypeIDField;
            }
            set {
                if ((this.ShaftTypeIDField.Equals(value) != true)) {
                    this.ShaftTypeIDField = value;
                    this.RaisePropertyChanged("ShaftTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShaftTypeName {
            get {
                return this.ShaftTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShaftTypeNameField, value) != true)) {
                    this.ShaftTypeNameField = value;
                    this.RaisePropertyChanged("ShaftTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quote", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class Quote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OrderTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuoteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tmag.GvcPassThroughApi.GvCommerce.QuoteItem[] QuoteItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderTotal {
            get {
                return this.OrderTotalField;
            }
            set {
                if ((this.OrderTotalField.Equals(value) != true)) {
                    this.OrderTotalField = value;
                    this.RaisePropertyChanged("OrderTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuoteId {
            get {
                return this.QuoteIdField;
            }
            set {
                if ((object.ReferenceEquals(this.QuoteIdField, value) != true)) {
                    this.QuoteIdField = value;
                    this.RaisePropertyChanged("QuoteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tmag.GvcPassThroughApi.GvCommerce.QuoteItem[] QuoteItems {
            get {
                return this.QuoteItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuoteItemsField, value) != true)) {
                    this.QuoteItemsField = value;
                    this.RaisePropertyChanged("QuoteItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuoteItem", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class QuoteItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ItemPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuoteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShaftTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShaftTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIDField, value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ItemPrice {
            get {
                return this.ItemPriceField;
            }
            set {
                if ((this.ItemPriceField.Equals(value) != true)) {
                    this.ItemPriceField = value;
                    this.RaisePropertyChanged("ItemPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModelID {
            get {
                return this.ModelIDField;
            }
            set {
                if ((this.ModelIDField.Equals(value) != true)) {
                    this.ModelIDField = value;
                    this.RaisePropertyChanged("ModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductTypeID {
            get {
                return this.ProductTypeIDField;
            }
            set {
                if ((this.ProductTypeIDField.Equals(value) != true)) {
                    this.ProductTypeIDField = value;
                    this.RaisePropertyChanged("ProductTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductTypeName {
            get {
                return this.ProductTypeNameField;
            }
            set {
                if ((this.ProductTypeNameField.Equals(value) != true)) {
                    this.ProductTypeNameField = value;
                    this.RaisePropertyChanged("ProductTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuoteID {
            get {
                return this.QuoteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.QuoteIDField, value) != true)) {
                    this.QuoteIDField = value;
                    this.RaisePropertyChanged("QuoteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShaftTypeID {
            get {
                return this.ShaftTypeIDField;
            }
            set {
                if ((this.ShaftTypeIDField.Equals(value) != true)) {
                    this.ShaftTypeIDField = value;
                    this.RaisePropertyChanged("ShaftTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShaftTypeName {
            get {
                return this.ShaftTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShaftTypeNameField, value) != true)) {
                    this.ShaftTypeNameField = value;
                    this.RaisePropertyChanged("ShaftTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeIn", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class TradeIn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Tmag.GvcPassThroughApi.GvCommerce.Address CustomerAddressField;
        
        private string CustomerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tmag.GvcPassThroughApi.GvCommerce.NVIActionEnum NVIActionField;
        
        private string ReferenceIDField;
        
        private Tmag.GvcPassThroughApi.GvCommerce.TradeInItem[] TradeInItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Tmag.GvcPassThroughApi.GvCommerce.Address CustomerAddress {
            get {
                return this.CustomerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressField, value) != true)) {
                    this.CustomerAddressField = value;
                    this.RaisePropertyChanged("CustomerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerEmail {
            get {
                return this.CustomerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerEmailField, value) != true)) {
                    this.CustomerEmailField = value;
                    this.RaisePropertyChanged("CustomerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tmag.GvcPassThroughApi.GvCommerce.NVIActionEnum NVIAction {
            get {
                return this.NVIActionField;
            }
            set {
                if ((this.NVIActionField.Equals(value) != true)) {
                    this.NVIActionField = value;
                    this.RaisePropertyChanged("NVIAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ReferenceID {
            get {
                return this.ReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIDField, value) != true)) {
                    this.ReferenceIDField = value;
                    this.RaisePropertyChanged("ReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Tmag.GvcPassThroughApi.GvCommerce.TradeInItem[] TradeInItems {
            get {
                return this.TradeInItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeInItemsField, value) != true)) {
                    this.TradeInItemsField = value;
                    this.RaisePropertyChanged("TradeInItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine3Field;
        
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryAbbrvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        private string StateProvinceField;
        
        private string ToNameField;
        
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine3 {
            get {
                return this.AddressLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine3Field, value) != true)) {
                    this.AddressLine3Field = value;
                    this.RaisePropertyChanged("AddressLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryAbbrv {
            get {
                return this.CountryAbbrvField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryAbbrvField, value) != true)) {
                    this.CountryAbbrvField = value;
                    this.RaisePropertyChanged("CountryAbbrv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string StateProvince {
            get {
                return this.StateProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.StateProvinceField, value) != true)) {
                    this.StateProvinceField = value;
                    this.RaisePropertyChanged("StateProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ToName {
            get {
                return this.ToNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ToNameField, value) != true)) {
                    this.ToNameField = value;
                    this.RaisePropertyChanged("ToName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NVIActionEnum", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    public enum NVIActionEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Return = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dispose = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeInItem", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class TradeInItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ItemPriceField;
        
        private int ModelIDField;
        
        private int ProductTypeIDField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SetPieceCountField;
        
        private int ShaftTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ItemPrice {
            get {
                return this.ItemPriceField;
            }
            set {
                if ((this.ItemPriceField.Equals(value) != true)) {
                    this.ItemPriceField = value;
                    this.RaisePropertyChanged("ItemPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ModelID {
            get {
                return this.ModelIDField;
            }
            set {
                if ((this.ModelIDField.Equals(value) != true)) {
                    this.ModelIDField = value;
                    this.RaisePropertyChanged("ModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductTypeID {
            get {
                return this.ProductTypeIDField;
            }
            set {
                if ((this.ProductTypeIDField.Equals(value) != true)) {
                    this.ProductTypeIDField = value;
                    this.RaisePropertyChanged("ProductTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SetPieceCount {
            get {
                return this.SetPieceCountField;
            }
            set {
                if ((this.SetPieceCountField.Equals(value) != true)) {
                    this.SetPieceCountField = value;
                    this.RaisePropertyChanged("SetPieceCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ShaftTypeID {
            get {
                return this.ShaftTypeIDField;
            }
            set {
                if ((this.ShaftTypeIDField.Equals(value) != true)) {
                    this.ShaftTypeIDField = value;
                    this.RaisePropertyChanged("ShaftTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceResponse", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.BatchTradeInResponse))]
    public partial class WebServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TimeMillisecondsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TimeMilliseconds {
            get {
                return this.TimeMillisecondsField;
            }
            set {
                if ((this.TimeMillisecondsField.Equals(value) != true)) {
                    this.TimeMillisecondsField = value;
                    this.RaisePropertyChanged("TimeMilliseconds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchTradeInResponse", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class BatchTradeInResponse : Tmag.GvcPassThroughApi.GvCommerce.WebServiceResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> FailedTradeInsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tmag.GvcPassThroughApi.GvCommerce.TradeInResponse[] SuccessfulTradeInsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> FailedTradeIns {
            get {
                return this.FailedTradeInsField;
            }
            set {
                if ((object.ReferenceEquals(this.FailedTradeInsField, value) != true)) {
                    this.FailedTradeInsField = value;
                    this.RaisePropertyChanged("FailedTradeIns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tmag.GvcPassThroughApi.GvCommerce.TradeInResponse[] SuccessfulTradeIns {
            get {
                return this.SuccessfulTradeInsField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessfulTradeInsField, value) != true)) {
                    this.SuccessfulTradeInsField = value;
                    this.RaisePropertyChanged("SuccessfulTradeIns");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeInResponse", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class TradeInResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublicTradeInIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuoteTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RANumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tmag.GvcPassThroughApi.GvCommerce.TradeInItemResponse[] TradeInItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublicTradeInID {
            get {
                return this.PublicTradeInIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicTradeInIDField, value) != true)) {
                    this.PublicTradeInIDField = value;
                    this.RaisePropertyChanged("PublicTradeInID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal QuoteTotal {
            get {
                return this.QuoteTotalField;
            }
            set {
                if ((this.QuoteTotalField.Equals(value) != true)) {
                    this.QuoteTotalField = value;
                    this.RaisePropertyChanged("QuoteTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RANumber {
            get {
                return this.RANumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RANumberField, value) != true)) {
                    this.RANumberField = value;
                    this.RaisePropertyChanged("RANumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceID {
            get {
                return this.ReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIDField, value) != true)) {
                    this.ReferenceIDField = value;
                    this.RaisePropertyChanged("ReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tmag.GvcPassThroughApi.GvCommerce.TradeInItemResponse[] TradeInItems {
            get {
                return this.TradeInItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeInItemsField, value) != true)) {
                    this.TradeInItemsField = value;
                    this.RaisePropertyChanged("TradeInItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeInItemResponse", Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09")]
    [System.SerializableAttribute()]
    public partial class TradeInItemResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuotePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SetPieceCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShaftTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((this.ItemIDField.Equals(value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineItem {
            get {
                return this.LineItemField;
            }
            set {
                if ((this.LineItemField.Equals(value) != true)) {
                    this.LineItemField = value;
                    this.RaisePropertyChanged("LineItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModelID {
            get {
                return this.ModelIDField;
            }
            set {
                if ((this.ModelIDField.Equals(value) != true)) {
                    this.ModelIDField = value;
                    this.RaisePropertyChanged("ModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductTypeID {
            get {
                return this.ProductTypeIDField;
            }
            set {
                if ((this.ProductTypeIDField.Equals(value) != true)) {
                    this.ProductTypeIDField = value;
                    this.RaisePropertyChanged("ProductTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal QuotePrice {
            get {
                return this.QuotePriceField;
            }
            set {
                if ((this.QuotePriceField.Equals(value) != true)) {
                    this.QuotePriceField = value;
                    this.RaisePropertyChanged("QuotePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SetPieceCount {
            get {
                return this.SetPieceCountField;
            }
            set {
                if ((this.SetPieceCountField.Equals(value) != true)) {
                    this.SetPieceCountField = value;
                    this.RaisePropertyChanged("SetPieceCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShaftTypeID {
            get {
                return this.ShaftTypeIDField;
            }
            set {
                if ((this.ShaftTypeIDField.Equals(value) != true)) {
                    this.ShaftTypeIDField = value;
                    this.RaisePropertyChanged("ShaftTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://pubservices.gvcommerce.com/PriceBookService/2014/09", ConfigurationName="GvCommerce.IPriceBookService")]
    public interface IPriceBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "PriceBookFull", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "PriceBookFullResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "PriceBookFullPriceBookFaultFault", Name="PriceBookFault")]
        Tmag.GvcPassThroughApi.GvCommerce.PriceBookItem[] GetPriceBookFull();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "PriceBookFull", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "PriceBookFullResponse")]
        System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.PriceBookItem[]> GetPriceBookFullAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "PriceBookItems", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "PriceBookItemsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "PriceBookItemsPriceBookFaultFault", Name="PriceBookFault")]
        Tmag.GvcPassThroughApi.GvCommerce.PriceBookItem[] GetPriceBookItems(Tmag.GvcPassThroughApi.GvCommerce.PriceBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "PriceBookItems", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "PriceBookItemsResponse")]
        System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.PriceBookItem[]> GetPriceBookItemsAsync(Tmag.GvcPassThroughApi.GvCommerce.PriceBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ProductTypeList", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ProductTypeListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ProductTypeListPriceBookFaultFault", Name="PriceBookFault")]
        Tmag.GvcPassThroughApi.GvCommerce.ProductType[] GetProductTypeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ProductTypeList", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ProductTypeListResponse")]
        System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.ProductType[]> GetProductTypeListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "BrandList", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "BrandListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "BrandListPriceBookFaultFault", Name="PriceBookFault")]
        Tmag.GvcPassThroughApi.GvCommerce.Brand[] GetBrandList(int productTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "BrandList", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "BrandListResponse")]
        System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Brand[]> GetBrandListAsync(int productTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ModelList", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ModelListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ModelListPriceBookFaultFault", Name="PriceBookFault")]
        Tmag.GvcPassThroughApi.GvCommerce.Model[] GetModelList(int productTypeID, int brandID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ModelList", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ModelListResponse")]
        System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Model[]> GetModelListAsync(int productTypeID, int brandID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ShaftList", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ShaftListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ShaftListPriceBookFaultFault", Name="PriceBookFault")]
        Tmag.GvcPassThroughApi.GvCommerce.ShaftType[] GetShaftList(int productTypeID, int brandID, int modelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ShaftList", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ShaftListResponse")]
        System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.ShaftType[]> GetShaftListAsync(int productTypeID, int brandID, int modelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ItemPrice", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ItemPriceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ItemPricePriceBookFaultFault", Name="PriceBookFault")]
        decimal GetItemPrice(int productTypeID, int brandID, int modelID, int shaftTypeID, int setPieceCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ItemPrice", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "ItemPriceResponse")]
        System.Threading.Tasks.Task<decimal> GetItemPriceAsync(int productTypeID, int brandID, int modelID, int shaftTypeID, int setPieceCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "QuoteByID", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "QuoteByIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "QuoteByIDPriceBookFaultFault", Name="PriceBookFault")]
        Tmag.GvcPassThroughApi.GvCommerce.Quote GetQuoteByID(string quoteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "QuoteByID", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "QuoteByIDResponse")]
        System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Quote> GetQuoteByIDAsync(string quoteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Add" +
            "ItemToQuote", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Add" +
            "ItemToQuoteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Add" +
            "ItemToQuotePriceBookFaultFault", Name="PriceBookFault")]
        Tmag.GvcPassThroughApi.GvCommerce.Quote AddItemToQuote(string quoteID, int productTypeID, int brandID, int modelID, int shaftTypeID, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Add" +
            "ItemToQuote", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Add" +
            "ItemToQuoteResponse")]
        System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Quote> AddItemToQuoteAsync(string quoteID, int productTypeID, int brandID, int modelID, int shaftTypeID, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Rem" +
            "oveItemFromQuote", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Rem" +
            "oveItemFromQuoteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Rem" +
            "oveItemFromQuotePriceBookFaultFault", Name="PriceBookFault")]
        Tmag.GvcPassThroughApi.GvCommerce.Quote RemoveItemFromQuote(string quoteID, string itemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Rem" +
            "oveItemFromQuote", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Rem" +
            "oveItemFromQuoteResponse")]
        System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Quote> RemoveItemFromQuoteAsync(string quoteID, string itemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Upd" +
            "ateItemQuantity", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Upd" +
            "ateItemQuantityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Upd" +
            "ateItemQuantityPriceBookFaultFault", Name="PriceBookFault")]
        Tmag.GvcPassThroughApi.GvCommerce.Quote UpdateItemQuantity(string quoteID, string itemID, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Upd" +
            "ateItemQuantity", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Upd" +
            "ateItemQuantityResponse")]
        System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Quote> UpdateItemQuantityAsync(string quoteID, string itemID, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Sav" +
            "eQuoteByEmailAddress", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Sav" +
            "eQuoteByEmailAddressResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Sav" +
            "eQuoteByEmailAddressPriceBookFaultFault", Name="PriceBookFault")]
        void SaveQuoteByEmailAddress(string quoteID, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Sav" +
            "eQuoteByEmailAddress", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Sav" +
            "eQuoteByEmailAddressResponse")]
        System.Threading.Tasks.Task SaveQuoteByEmailAddressAsync(string quoteID, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "QuoteByEmailAddress", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "QuoteByEmailAddressResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "QuoteByEmailAddressPriceBookFaultFault", Name="PriceBookFault")]
        Tmag.GvcPassThroughApi.GvCommerce.Quote GetQuoteByEmailAddress(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "QuoteByEmailAddress", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Get" +
            "QuoteByEmailAddressResponse")]
        System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Quote> GetQuoteByEmailAddressAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Pro" +
            "cessBatchTradeIn", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Pro" +
            "cessBatchTradeInResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tmag.GvcPassThroughApi.GvCommerce.PriceBookFault), Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Pro" +
            "cessBatchTradeInPriceBookFaultFault", Name="PriceBookFault")]
        Tmag.GvcPassThroughApi.GvCommerce.BatchTradeInResponse ProcessBatchTradeIn(Tmag.GvcPassThroughApi.GvCommerce.TradeIn[] TradeIns);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Pro" +
            "cessBatchTradeIn", ReplyAction="https://pubservices.gvcommerce.com/PriceBookService/2014/09/IPriceBookService/Pro" +
            "cessBatchTradeInResponse")]
        System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.BatchTradeInResponse> ProcessBatchTradeInAsync(Tmag.GvcPassThroughApi.GvCommerce.TradeIn[] TradeIns);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPriceBookServiceChannel : Tmag.GvcPassThroughApi.GvCommerce.IPriceBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PriceBookServiceClient : System.ServiceModel.ClientBase<Tmag.GvcPassThroughApi.GvCommerce.IPriceBookService>, Tmag.GvcPassThroughApi.GvCommerce.IPriceBookService {
        
        public PriceBookServiceClient() {
        }
        
        public PriceBookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PriceBookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceBookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceBookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tmag.GvcPassThroughApi.GvCommerce.PriceBookItem[] GetPriceBookFull() {
            return base.Channel.GetPriceBookFull();
        }
        
        public System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.PriceBookItem[]> GetPriceBookFullAsync() {
            return base.Channel.GetPriceBookFullAsync();
        }
        
        public Tmag.GvcPassThroughApi.GvCommerce.PriceBookItem[] GetPriceBookItems(Tmag.GvcPassThroughApi.GvCommerce.PriceBookRequest request) {
            return base.Channel.GetPriceBookItems(request);
        }
        
        public System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.PriceBookItem[]> GetPriceBookItemsAsync(Tmag.GvcPassThroughApi.GvCommerce.PriceBookRequest request) {
            return base.Channel.GetPriceBookItemsAsync(request);
        }
        
        public Tmag.GvcPassThroughApi.GvCommerce.ProductType[] GetProductTypeList() {
            return base.Channel.GetProductTypeList();
        }
        
        public System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.ProductType[]> GetProductTypeListAsync() {
            return base.Channel.GetProductTypeListAsync();
        }
        
        public Tmag.GvcPassThroughApi.GvCommerce.Brand[] GetBrandList(int productTypeID) {
            return base.Channel.GetBrandList(productTypeID);
        }
        
        public System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Brand[]> GetBrandListAsync(int productTypeID) {
            return base.Channel.GetBrandListAsync(productTypeID);
        }
        
        public Tmag.GvcPassThroughApi.GvCommerce.Model[] GetModelList(int productTypeID, int brandID) {
            return base.Channel.GetModelList(productTypeID, brandID);
        }
        
        public System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Model[]> GetModelListAsync(int productTypeID, int brandID) {
            return base.Channel.GetModelListAsync(productTypeID, brandID);
        }
        
        public Tmag.GvcPassThroughApi.GvCommerce.ShaftType[] GetShaftList(int productTypeID, int brandID, int modelID) {
            return base.Channel.GetShaftList(productTypeID, brandID, modelID);
        }
        
        public System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.ShaftType[]> GetShaftListAsync(int productTypeID, int brandID, int modelID) {
            return base.Channel.GetShaftListAsync(productTypeID, brandID, modelID);
        }
        
        public decimal GetItemPrice(int productTypeID, int brandID, int modelID, int shaftTypeID, int setPieceCount) {
            return base.Channel.GetItemPrice(productTypeID, brandID, modelID, shaftTypeID, setPieceCount);
        }
        
        public System.Threading.Tasks.Task<decimal> GetItemPriceAsync(int productTypeID, int brandID, int modelID, int shaftTypeID, int setPieceCount) {
            return base.Channel.GetItemPriceAsync(productTypeID, brandID, modelID, shaftTypeID, setPieceCount);
        }
        
        public Tmag.GvcPassThroughApi.GvCommerce.Quote GetQuoteByID(string quoteID) {
            return base.Channel.GetQuoteByID(quoteID);
        }
        
        public System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Quote> GetQuoteByIDAsync(string quoteID) {
            return base.Channel.GetQuoteByIDAsync(quoteID);
        }
        
        public Tmag.GvcPassThroughApi.GvCommerce.Quote AddItemToQuote(string quoteID, int productTypeID, int brandID, int modelID, int shaftTypeID, int qty) {
            return base.Channel.AddItemToQuote(quoteID, productTypeID, brandID, modelID, shaftTypeID, qty);
        }
        
        public System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Quote> AddItemToQuoteAsync(string quoteID, int productTypeID, int brandID, int modelID, int shaftTypeID, int qty) {
            return base.Channel.AddItemToQuoteAsync(quoteID, productTypeID, brandID, modelID, shaftTypeID, qty);
        }
        
        public Tmag.GvcPassThroughApi.GvCommerce.Quote RemoveItemFromQuote(string quoteID, string itemID) {
            return base.Channel.RemoveItemFromQuote(quoteID, itemID);
        }
        
        public System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Quote> RemoveItemFromQuoteAsync(string quoteID, string itemID) {
            return base.Channel.RemoveItemFromQuoteAsync(quoteID, itemID);
        }
        
        public Tmag.GvcPassThroughApi.GvCommerce.Quote UpdateItemQuantity(string quoteID, string itemID, int qty) {
            return base.Channel.UpdateItemQuantity(quoteID, itemID, qty);
        }
        
        public System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Quote> UpdateItemQuantityAsync(string quoteID, string itemID, int qty) {
            return base.Channel.UpdateItemQuantityAsync(quoteID, itemID, qty);
        }
        
        public void SaveQuoteByEmailAddress(string quoteID, string emailAddress) {
            base.Channel.SaveQuoteByEmailAddress(quoteID, emailAddress);
        }
        
        public System.Threading.Tasks.Task SaveQuoteByEmailAddressAsync(string quoteID, string emailAddress) {
            return base.Channel.SaveQuoteByEmailAddressAsync(quoteID, emailAddress);
        }
        
        public Tmag.GvcPassThroughApi.GvCommerce.Quote GetQuoteByEmailAddress(string emailAddress) {
            return base.Channel.GetQuoteByEmailAddress(emailAddress);
        }
        
        public System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.Quote> GetQuoteByEmailAddressAsync(string emailAddress) {
            return base.Channel.GetQuoteByEmailAddressAsync(emailAddress);
        }
        
        public Tmag.GvcPassThroughApi.GvCommerce.BatchTradeInResponse ProcessBatchTradeIn(Tmag.GvcPassThroughApi.GvCommerce.TradeIn[] TradeIns) {
            return base.Channel.ProcessBatchTradeIn(TradeIns);
        }
        
        public System.Threading.Tasks.Task<Tmag.GvcPassThroughApi.GvCommerce.BatchTradeInResponse> ProcessBatchTradeInAsync(Tmag.GvcPassThroughApi.GvCommerce.TradeIn[] TradeIns) {
            return base.Channel.ProcessBatchTradeInAsync(TradeIns);
        }
    }
}
